// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errno.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "errno.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sglib {
namespace errorcode {

namespace {

const ::google::protobuf::EnumDescriptor* EErrorCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_errno_2eproto() {
  protobuf_AddDesc_errno_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "errno.proto");
  GOOGLE_CHECK(file != NULL);
  EErrorCode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_errno_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_errno_2eproto() {
}

void protobuf_AddDesc_errno_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013errno.proto\022\017sglib.errorcode*\351\006\n\nEErro"
    "rCode\022\027\n\023E_ErrorCode_Success\020\000\022 \n\023E_Erro"
    "rCode_Unknown\020\377\377\377\377\377\377\377\377\377\001\022#\n\026E_ErrorCode_"
    "StateError\020\376\377\377\377\377\377\377\377\377\001\022!\n\024E_ErrorCode_Reg"
    "Error\020\375\377\377\377\377\377\377\377\377\001\022#\n\026E_ErrorCode_LoginErr"
    "or\020\374\377\377\377\377\377\377\377\377\001\022#\n\026E_ErrorCode_NoSuchGame\020"
    "\233\377\377\377\377\377\377\377\377\001\022%\n\030E_ErrorCode_GameUserFull\020\232"
    "\377\377\377\377\377\377\377\377\001\022%\n\030E_ErrorCode_NotLoginGame\020\231\377"
    "\377\377\377\377\377\377\377\001\022)\n\034E_ErrorCode_AleardyLoginGame"
    "\020\230\377\377\377\377\377\377\377\377\001\022#\n\026E_ErrorCode_NoThisRoom\020\267\376"
    "\377\377\377\377\377\377\377\001\022#\n\026E_ErrorCode_RoomIsFull\020\266\376\377\377\377"
    "\377\377\377\377\001\022%\n\030E_ErrorCode_RoomPwdError\020\265\376\377\377\377\377"
    "\377\377\377\001\022&\n\031E_ErrorCode_AleardyInRoom\020\264\376\377\377\377\377"
    "\377\377\377\001\022)\n\034E_ErrorCode_CreateGroupError\020\323\375\377"
    "\377\377\377\377\377\377\001\022&\n\031E_ErrorCode_NotFoundGroup\020\322\375\377"
    "\377\377\377\377\377\377\001\022+\n\036E_ErrorCode_NotFoundLoginGrou"
    "p\020\321\375\377\377\377\377\377\377\377\001\022\'\n\032E_ErrorCode_NotInThisGro"
    "up\020\320\375\377\377\377\377\377\377\377\001\022(\n\033E_ErrorCode_NoThisGroup"
    "Game\020\317\375\377\377\377\377\377\377\377\001\022&\n\031E_ErrorCode_NotEnough"
    "Room\020\316\375\377\377\377\377\377\377\377\001\022,\n\037E_ErrorCode_NotInvite"
    "dJoinGroup\020\315\375\377\377\377\377\377\377\377\001\022(\n\033E_ErrorCode_Joi"
    "nGroupFailed\020\314\375\377\377\377\377\377\377\377\001\022)\n\034E_ErrorCode_T"
    "etris_NotInRoom\020\357\261\377\377\377\377\377\377\377\001", 906);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "errno.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_errno_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_errno_2eproto {
  StaticDescriptorInitializer_errno_2eproto() {
    protobuf_AddDesc_errno_2eproto();
  }
} static_descriptor_initializer_errno_2eproto_;
const ::google::protobuf::EnumDescriptor* EErrorCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EErrorCode_descriptor_;
}
bool EErrorCode_IsValid(int value) {
  switch(value) {
    case -10001:
    case -308:
    case -307:
    case -306:
    case -305:
    case -304:
    case -303:
    case -302:
    case -301:
    case -204:
    case -203:
    case -202:
    case -201:
    case -104:
    case -103:
    case -102:
    case -101:
    case -4:
    case -3:
    case -2:
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace errorcode
}  // namespace sglib

// @@protoc_insertion_point(global_scope)
